# Generated by Django 3.2.15 on 2022-09-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.portfolio'),
        ),
    ]
